title: Antipodean Traveller
email: hamishjgray@gmail.com
description: Follow the adventures of a small Kiwi travelling the world!
baseurl: ""
url: ""
twitter_username:
github_username:

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - gulpfile.js
  - package.json
  - bower_components
  - bower.json
  - README.md
